esphome:
  name: test-lilygo
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: components

logger:

wifi:
  ssid: "test"
  password: "test1234"

display:
  - platform: lilygo_t5_47_display
    id: t5_display
    update_interval: 60s
    lambda: |-
      it.print(100, 100, id(roboto), "Hello World!");

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 20

sensor:
  - platform: lilygo_t5_47_battery
    voltage:
      name: "Battery Voltage"
